/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_munger_stereocamera_service_PhotoProcessor_CompositeImageType */

#ifndef _Included_com_munger_stereocamera_service_PhotoProcessor_CompositeImageType
#define _Included_com_munger_stereocamera_service_PhotoProcessor_CompositeImageType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
