/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_munger_stereocamera_utility_PhotoProcessor */

#ifndef _Included_com_munger_stereocamera_utility_PhotoProcessor
#define _Included_com_munger_stereocamera_utility_PhotoProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_munger_stereocamera_utility_PhotoProcessor
 * Method:    initN
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_munger_stereocamera_utility_PhotoProcessor_initN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_munger_stereocamera_utility_PhotoProcessor
 * Method:    setImageN
 * Signature: (ZLjava/lang/String;IFII)V
 */
JNIEXPORT void JNICALL Java_com_munger_stereocamera_utility_PhotoProcessor_setImageN
  (JNIEnv *, jobject, jboolean, jstring, jint, jfloat, jint, jint);

/*
 * Class:     com_munger_stereocamera_utility_PhotoProcessor
 * Method:    processN
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_munger_stereocamera_utility_PhotoProcessor_processN
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     com_munger_stereocamera_utility_PhotoProcessor
 * Method:    getProcessedPathN
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_munger_stereocamera_utility_PhotoProcessor_getProcessedPathN
  (JNIEnv *, jobject);

/*
 * Class:     com_munger_stereocamera_utility_PhotoProcessor
 * Method:    getProcessedDimension
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_munger_stereocamera_utility_PhotoProcessor_getProcessedDimension
  (JNIEnv *, jobject);

/*
 * Class:     com_munger_stereocamera_utility_PhotoProcessor
 * Method:    cleanUpN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_munger_stereocamera_utility_PhotoProcessor_cleanUpN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
