/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_munger_stereocamera_utility_PhotoProcessor_PhotoStruct */

#ifndef _Included_com_munger_stereocamera_utility_PhotoProcessor_PhotoStruct
#define _Included_com_munger_stereocamera_utility_PhotoProcessor_PhotoStruct
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
