package com.munger.stereocamera.ip.command;

/**
 * Created by hallmarklabs on 2/23/18.
 */

public enum BluetoothCommands
{
	NONE,
	FIRE_SHUTTER,
	PING,
	LATENCY_CHECK,
	RECEIVE_ANGLE_OF_VIEW,
	SET_ZOOM,
	SET_FACING,
	SET_OVERLAY,
	SEND_VERSION,
	RECEIVE_ZOOM,
	RECEIVE_STATUS,
	RECEIVE_GRAVITY,
	RECEIVE_ORIENTATION,
	CONNECTION_PAUSE,
	RECEIVE_CONNECTION_PAUSE,
	DISCONNECT,
	RECEIVE_DISCONNECT,
	SEND_PROCESSED_PHOTO,
	RECEIVE_PREVIEW_FRAME,
	HANDSHAKE,
}
